[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
verbosity = 5
fuzz_runs = 100
optimizer = true
optimizer_runs = 200

# --- ASEGÚRATE DE QUE ESTO ESTÉ AL FINAL ---
[dependencies]

# Para AccessControl, ReentrancyGuard, SafeERC20 (feedback TP3)
openzeppelin-contracts = "OpenZeppelin/openzeppelin-contracts"

# Para IUniswapV2Router02 (requisito TP4)
uniswap-v2-periphery = "Uniswap/v2-periphery"